name: "Update Changelog"

on:
    workflow_call:
        inputs:
            branch:
                description: 'Target branch'
                default: ${{ github.event.release.target_commitish }}
                type: string
            version:
                description: 'Released version'
                default: ${{ github.event.release.tag_name }}
                type: string
            notes:
                description: 'Release notes'
                default: ${{ github.event.release.body }}
                type: string

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  ref: main
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract release date from git tag
              id: release_date
              run: |
                  # Get UNIX timestamp from git-tag
                  TIMESTAMP_OF_RELEASE_COMMIT=$(git log -1 --date=unix --format=%ad '${{ inputs.version }}');
                  
                  # Convert timestamp to UTC date in Y-m-d format
                  FORMATED_DATE=$(date -u -d @$TIMESTAMP_OF_RELEASE_COMMIT +%Y-%m-%d)
                  
                  # Make date available to other steps
                  echo "date=$(echo $FORMATED_DATE)" >> $GITHUB_OUTPUT;

            - name: Update Changelog
              uses: stefanzweifel/changelog-updater-action@v1
              with:
                  # Pass extracted release date, release notes and version to the Action.
                  release-date: ${{ steps.release_date.outputs.date }}
                  release-notes: ${{ inputs.notes }}
                  latest-version: ${{ inputs.version }}
                  compare-url-target-revision: ${{ inputs.branch }}
                  parse-github-usernames: true

            - name: Commit updated CHANGELOG
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  branch: main
                  commit_message: Update CHANGELOG
                  push_options: --force
                  file_pattern: CHANGELOG.md
